# Generated by Django 5.1.5 on 2025-01-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
